/**
 * Traduzioni dell'interfaccia. **Inglese di default**, italiano secondario:
 * il sito di 13protein.com è di fatto monolingua inglese (WPML installato ma
 * senza contenuti tradotti), quindi l'italiano qui è una traduzione nostra, non
 * copy approvato dal cliente.
 *
 * Segnaposto: i testi della landing e della chat vanno riscritti quando saranno
 * definiti i compiti veri dell'agente.
 */
export const translations = {
	en: {
		landing: {
			title: "13 Protein · Project assistant",
			subtitle:
				"Tell us about your supplement project. The assistant collects what our team needs to prepare a quote, and answers questions about how we manufacture.",
			start: "Start",
			disclaimer: "Placeholder page: copy to be written with the client.",
			langLabel: "Italiano",
		},
		chat: {
			title: "Project assistant",
			typingVariants: [
				"The assistant is thinking…",
				"The assistant is checking the knowledge base…",
				"The assistant is putting the answer together…",
			],
			inputPlaceholder: "Write your answer…",
			inputDisabled: "Pick one of the options above…",
			sendButton: "Send",
			reloadTooltip: "Start the conversation over",
			reloadConfirm: "Start the conversation over?",
			reloadYes: "Yes, start over",
			reloadNo: "Cancel",
			skipTooltip: "Skip conversation",
			skipConfirm:
				"Skip the rest of the conversation? Answers already given are kept, the rest is filled in with example data.",
			skipYes: "Yes, skip",
			skipNo: "Cancel",
			sendError: "Connection problem. **Try sending the message again.**",
			initError: "I cannot reach the assistant right now. **Reload the page to retry.**",
			// Riga minima che assolve l'art. 50.1 AI Act (stai parlando con un'IA) e
			// rinvia all'informativa per tutto il resto. Vive nella schermata di
			// chat, non solo sulla landing: il pulsante ↻ rientra qui saltando la
			// landing. Non accorciare oltre: sotto questa soglia si perde l'art.
			// 50.1 (menzione dell'IA) o l'art. 13 (link).
			aiDisclosure: "Answers are generated by an artificial intelligence.",
			aiDisclosureLink: "Privacy notice",
		},
		leadSummary: {
			title: "Your request",
			subtitle: "This is what will reach the 13 Protein team.",
			fields: {
				profile: "Profile",
				category: "Category",
				format: "Format",
				projectDescription: "Project",
				questionsAsked: "Questions asked",
				topicsCited: "Pages cited",
				quoteRequested: "Quote requested",
				contact: "Contact",
			},
			yes: "Yes",
			no: "No",
			empty: "Not provided",
		},
		testing: {
			title: "Testing environment",
			user: "User",
			password: "Password",
			signIn: "Sign in",
			signingIn: "Signing in…",
		},
	},
	it: {
		landing: {
			title: "13 Protein · Assistente di progetto",
			subtitle:
				"Ci racconti il suo progetto di integratori. L'assistente raccoglie quello che serve al nostro team per preparare un preventivo e risponde alle domande su come produciamo.",
			start: "Inizia",
			disclaimer: "Pagina segnaposto: i testi vanno scritti con il cliente.",
			langLabel: "English",
		},
		chat: {
			title: "Assistente di progetto",
			typingVariants: [
				"L'assistente sta pensando…",
				"L'assistente sta consultando il knowledge base…",
				"L'assistente sta componendo la risposta…",
			],
			inputPlaceholder: "Scriva la sua risposta…",
			inputDisabled: "Scelga una delle opzioni qui sopra…",
			sendButton: "Invia",
			reloadTooltip: "Ricomincia la conversazione",
			reloadConfirm: "Vuole ricominciare la conversazione?",
			reloadYes: "Sì, ricomincia",
			reloadNo: "Annulla",
			skipTooltip: "Salta conversazione",
			skipConfirm:
				"Vuole saltare il resto della conversazione? I campi già raccolti vengono mantenuti, gli altri vengono compilati con dati di esempio.",
			skipYes: "Sì, salta",
			skipNo: "Annulla",
			sendError: "Si è verificato un problema di connessione. **Riprovi a inviare il messaggio.**",
			initError: "Non riesco a raggiungere l'assistente in questo momento. **Ricarichi la pagina per riprovare.**",
			aiDisclosure: "Risposte generate da un'intelligenza artificiale.",
			aiDisclosureLink: "Informativa privacy",
		},
		leadSummary: {
			title: "La sua richiesta",
			subtitle: "È questo che arriverà al team di 13 Protein.",
			fields: {
				profile: "Profilo",
				category: "Categoria",
				format: "Formato",
				projectDescription: "Progetto",
				questionsAsked: "Domande poste",
				topicsCited: "Pagine citate",
				quoteRequested: "Preventivo richiesto",
				contact: "Contatto",
			},
			yes: "Sì",
			no: "No",
			empty: "Non indicato",
		},
		testing: {
			title: "Ambiente di test",
			user: "Utente",
			password: "Password",
			signIn: "Accedi",
			signingIn: "Accesso…",
		},
	},
};
