import { useLanguage } from "../../contexts/LanguageContext";
import "./PrivacyPolicy.css";

/**
 * Informativa privacy, servita su /privacy-policy (route in App.jsx; il
 * fallback SPA del server Node restituisce index.html).
 *
 * **SEGNAPOSTO.** Non è un'informativa: è l'ossatura da compilare con il
 * titolare del trattamento (13 e Protein Import AB) e con chi ne risponde
 * legalmente. Ogni valore di fatto — dati societari, DPO, termini di
 * conservazione, trasferimenti extra-UE, fornitori LLM — è ancora da decidere.
 * Finché resta così, non pubblicare questa pagina su un sito raggiungibile.
 *
 * I due oggetti it/en sono due testi separati, non una traduzione a runtime:
 * quando saranno testi veri, ogni valore di fatto andrà modificato su
 * entrambi i lati, o l'informativa dice due cose diverse a due utenti.
 */

const CONTENT = {
	en: {
		title: "Privacy notice",
		updated: "Placeholder, not yet drafted",
		back: "← Back to home",
		intro:
			"This page is a placeholder. The notice must be drafted with the data controller before the assistant is made available to anyone outside the project.",
		sections: [
			{
				h: "1. Controller",
				p: [
					"13 e Protein Import AB, Speditionsvägen 45, 142 50 Skogås, Sweden. Public contact: info@13protein.com.",
					"To be completed: registration number, representative, and whether a data protection officer is appointed.",
				],
			},
			{
				h: "2. What we process",
				p: [
					"**Conversation content** — what you write to the assistant: your project description and the questions you ask.",
					"**Contact details** — name, company and e-mail, collected only to prepare and send a quote.",
					"**Minimal usage statistics** — pseudonymous events (page view, click, conversation completed, quote requested), a random identifier stored in your browser, the interface language, and two coarse labels for device and browser family.",
					"To be completed: server logs, sub-processors, and the LLM provider that processes the conversation.",
				],
			},
			{
				h: "3. Purposes and legal bases",
				p: [
					"To be completed with the controller. The working assumption is pre-contractual measures (art. 6.1.b GDPR) for the quote, and legitimate interest for the aggregate usage statistics.",
				],
			},
			{
				h: "4. Retention",
				p: [
					"To be completed. The application ships with placeholder terms and the purge runs in dry run: nothing is deleted until the terms are decided and this section states them.",
				],
			},
			{
				h: "5. Your rights",
				p: [
					"Access, rectification, erasure, restriction, portability and objection (arts. 15 to 22 GDPR), and the right to lodge a complaint with a supervisory authority.",
					"To be completed: the address to use for these requests.",
				],
			},
			{
				h: "6. Automated processing",
				p: [
					"The assistant's answers are generated by an artificial intelligence (art. 50.1 AI Act). It does not take decisions that produce legal effects concerning you: a human reads every request before answering it.",
				],
			},
		],
	},
	it: {
		title: "Informativa sulla privacy",
		updated: "Segnaposto, non ancora redatta",
		back: "← Torna alla home",
		intro:
			"Questa pagina è un segnaposto. L'informativa va redatta con il titolare del trattamento prima che l'assistente sia raggiungibile da chiunque fuori dal progetto.",
		sections: [
			{
				h: "1. Titolare del trattamento",
				p: [
					"13 e Protein Import AB, Speditionsvägen 45, 142 50 Skogås, Svezia. Contatto pubblico: info@13protein.com.",
					"Da completare: numero di registrazione, rappresentante ed eventuale responsabile della protezione dei dati.",
				],
			},
			{
				h: "2. Quali dati trattiamo",
				p: [
					"**Contenuto della conversazione** — quello che scrive all'assistente: la descrizione del progetto e le domande poste.",
					"**Dati di contatto** — nome, azienda ed e-mail, raccolti solo per preparare e inviare un preventivo.",
					"**Statistiche d'uso minime** — eventi pseudonimi (visualizzazione della pagina, click, conversazione completata, preventivo richiesto), un identificativo casuale salvato nel browser, la lingua dell'interfaccia e due etichette generiche su dispositivo e famiglia di browser.",
					"Da completare: log del server, sub-responsabili e il fornitore LLM che elabora la conversazione.",
				],
			},
			{
				h: "3. Finalità e basi giuridiche",
				p: [
					"Da completare con il titolare. L'ipotesi di lavoro è l'esecuzione di misure precontrattuali (art. 6.1.b GDPR) per il preventivo e il legittimo interesse per le statistiche aggregate.",
				],
			},
			{
				h: "4. Conservazione",
				p: [
					"Da completare. L'applicazione parte con termini segnaposto e la purge gira in dry run: non si cancella nulla finché i termini non sono decisi e scritti qui.",
				],
			},
			{
				h: "5. I suoi diritti",
				p: [
					"Accesso, rettifica, cancellazione, limitazione, portabilità e opposizione (artt. da 15 a 22 GDPR), e diritto di reclamo a un'autorità di controllo.",
					"Da completare: l'indirizzo a cui rivolgere queste richieste.",
				],
			},
			{
				h: "6. Trattamenti automatizzati",
				p: [
					"Le risposte dell'assistente sono generate da un'intelligenza artificiale (art. 50.1 AI Act). Non prende decisioni con effetti giuridici nei suoi confronti: ogni richiesta viene letta da una persona prima di ricevere risposta.",
				],
			},
		],
	},
};

// **testo** → <strong>
function renderParagraph(text, key) {
	const parts = text.split(/\*\*(.+?)\*\*/g);
	return (
		<p key={key}>
			{parts.map((part, i) => (i % 2 === 1 ? <strong key={i}>{part}</strong> : part))}
		</p>
	);
}

export default function PrivacyPolicy() {
	const { language, localePath } = useLanguage();
	const content = CONTENT[language] || CONTENT.en;

	return (
		<div className="privacy-page">
			<div className="privacy-container">
				<a className="privacy-back" href={localePath("/")}>
					{content.back}
				</a>
				<h1>{content.title}</h1>
				<p className="privacy-updated">{content.updated}</p>
				<p className="privacy-intro">{content.intro}</p>
				{content.sections.map((section) => (
					<section key={section.h}>
						<h2>{section.h}</h2>
						{section.p.map((p, i) => renderParagraph(p, i))}
					</section>
				))}
			</div>
		</div>
	);
}
